MyShop.WebUI/Controllers/BasketController.cs
using MyShop.Core.Contracts;
using MyShop.Core.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MyShop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IRepositroy<Customer> customers;
        IBasketService basketService;
        IOrderService orderService;
        public BasketController(IBasketService basketService,IOrderService OrderService,IRepositroy<Customer> c)
        {
            this.basketService = basketService;
            this.orderService = OrderService;
            this.customers = c;
        }
        
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            
            return View(model);
        }
        public JsonResult AddToBasket(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);
            return Json("Success");
        }
        public ActionResult RemoveFromBasket(string Id)
        {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");

        }

        public JsonResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);
            
            return Json(basketSummary);

        }


        [Authorize]
        public ActionResult Checkout()
        {
            Customer customer = customers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);
            if (customer != null)
            {
                Order order = new Order()
                {
                    Email = customer.Email,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    State = customer.State,
                    ZipCode = customer.ZipCode,
                    Street = customer.Street,
                    City = customer.City

                };
                return View(order);

            }
            else
                return RedirectToAction("Error");
        }
        [HttpPost]
        [Authorize]
        public ActionResult Checkout(Order order)
        {
            order.Email = User.Identity.Name;
            var basketItems = basketService.GetBasketItems(this.HttpContext);
            order.OrderStatus = "Ordered Created";
            order.OrderStatus = "Payment Processed";
            orderService.CreateOrder(order, basketItems);
            basketService.ClearBasket(this.HttpContext);
            return RedirectToAction("Thankyou", new { OrderId = order.Id });

        }
        public ActionResult Thankyou(string OrderId)
        {
            ViewBag.OrderId = OrderId;
            return View();
        }
    }
}

MyShop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body  onload="BasketSummaryFetcher()">
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="@Url.Action("Index","Basket")"><div class="cart1"></div></a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Basket")"><div class="cart2"></div></a>
                </li>

               

            </ul>
                <script type="text/javascript">
                    function BasketSummaryFetcher() {
                        $.ajax(
                            {
                                type: 'post',
                                url: '/Basket/BasketSummary',
                                dataType: 'json',
                                success: function (data) {
                                    let BasketTotal, BasketCount;
                                    BasketCount = data.BasketCount;
                                    BasketTotal = data.BasketTotal;
                                    $("div.cart1").html(BasketCount + " items");
                                    $("div.cart2").html("$" + BasketTotal.toFixed(2));
                                },
                            });
                    }

                </script>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>